package com.example.myapplication2.api.codewars;

public enum SortBy {
    USERNAME_ASC, USERNAME_DESC,
    HONOR_ASC, HONOR_DESC,
    LEADERBOARD_POSITION_ASC, LEADERBOARD_POSITION_DESC,
    RANK_NAME_ASC, RANK_NAME_DESC,
    TOTAL_COMPLETED_KATA_ASC, TOTAL_COMPLETED_KATA_DESC
}
